<?php
declare(strict_types=1);

$common = [
    'curriculum' => 'LehrplanPLUS Bayern, Katholische Religionslehre, Qualifikationsphase; operatorengestützte kompetenzorientierte Rückmeldung',
    'minimum_chars' => 180,
    'maximum_chars' => 9000,
    'prompt_version' => 'kr12-feedback-2026-08-v1',
];

return [
    'frankl-zusammenfassen' => $common + [
        'title' => 'Frankls Projektionsmodell prägnant zusammenfassen',
        'operator' => 'zusammenfassen',
        'afb' => 'I',
        'level' => 'gA/eA',
        'material' => 'Viktor E. Frankls dimensionalontologisches Projektionsmodell: Einheit trotz Mannigfaltigkeit; ein Körper kann in niedrigeren Dimensionen widersprüchliche Schatten erzeugen, verschiedene Körper können denselben Schatten erzeugen. Wissenschaftliche Perspektiven sind richtige, aber begrenzte Projektionen des Menschen.',
        'criteria' => ['konkreter Gedankengang statt bloßer Themenangabe', 'Problem, beide Projektionsgesetze und anthropologische Folgerung', 'eigenständige, sachliche und prägnante Wiedergabe', 'keine persönliche Bewertung in der Zusammenfassung'],
    ],
    'frankl-analysieren' => $common + [
        'title' => 'Funktion der Projektionsgesetze analysieren',
        'operator' => 'analysieren',
        'afb' => 'II',
        'level' => 'gA/eA',
        'material' => 'Frankl verwendet geometrische Projektionen als methodische Analogie. Das erste Gesetz erklärt scheinbare Widersprüche zwischen Teilwissenschaften, das zweite warnt vor der Gleichsetzung identischer Beobachtungen mit identischer Wirklichkeit. Ziel ist eine nichtreduktionistische Einheit des Menschen.',
        'criteria' => ['Aufbau und Argumentationsschritte', 'Funktion beider Analogien', 'mindestens zwei präzise Textbezüge', 'Unterscheidung von Teilwahrheit und Reduktionismus', 'Argumentationsziel'],
    ],
    'frankl-beurteilen' => $common + [
        'title' => 'Frankls Modell auf KI-Bewusstsein beziehen',
        'operator' => 'beurteilen',
        'afb' => 'III',
        'level' => 'gA/eA',
        'material' => 'Das Projektionsmodell begrenzt Schlüsse von beobachtbarem Verhalten auf die ganze Wirklichkeit eines Wesens. Menschenähnliche Sprache kann funktionale Ähnlichkeit zeigen, beweist aber kein phänomenales Erleben. Das Modell entscheidet die Bewusstseinsfrage nicht allein.',
        'criteria' => ['offengelegte Urteilskriterien', 'sachgerechte Anwendung auf KI-Ausgaben', 'mindestens ein starker Einwand oder eine Grenze', 'Abwägung statt bloßer Position', 'klares begründetes Urteil'],
    ],
    'frankl-sinn-verantwortung' => $common + [
        'title' => 'Frankls Zeitdiagnose, Sinn und Verantwortung erschließen',
        'operator' => 'zusammenfassen und erläutern',
        'afb' => 'I–II',
        'level' => 'gA/eA',
        'material' => 'Frankl beschreibt ein Sinnlosigkeitsgefühl als Zeitdiagnose. Erziehung soll das Gewissen verfeinern, damit die konkrete Forderung einer einmaligen Situation wahrgenommen wird. Verantwortung bedeutet selektives Antworten auf konkreten Sinn; Konformismus und Totalitarismus erscheinen als Gefahren des existenziellen Vakuums.',
        'criteria' => ['konkreter Gedankengang statt Themenangabe', 'Zeitdiagnose und existenzielles Vakuum', 'Gewissen als Wahrnehmungsorgan der konkreten Forderung', 'Verantwortung und Einzigartigkeit von Situation und Person', 'begründeter Rückbezug auf die vorausgehenden Vermutungen'],
        'minimum_chars' => 320,
    ],
    'wissenskrise-bildanalyse' => $common + [
        'title' => 'Illustration zur Wissenskrise um 1900 analysieren',
        'operator' => 'beschreiben und interpretieren',
        'afb' => 'I–II',
        'level' => 'gA/eA',
        'material' => 'Die Illustration bündelt verschiedene visuelle Perspektiven auf den Menschen. Eine überzeugende Lösung beschreibt zunächst Komposition, Figur, Flächen, Linien, Überlagerungen, Farben und Kontraste, bevor sie das Integrationsproblem spezialisierter Wissenschaften deutet. Das Bild ist keine historische Quelle und liefert keine fertige Lösung.',
        'criteria' => ['Beschreibung konsequent vor Interpretation', 'Bildaufbau, Schwerpunkt und räumliche Anordnung', 'Farben, Figuren, Flächen, Linien, Überlagerungen und Kontraste', 'Teilperspektiven und fehlender Zusammenhang nachvollziehbar gedeutet', 'Grenze der Illustration als künstlerisches Deutungsangebot reflektiert'],
        'minimum_chars' => 260,
    ],
    'tiefenzeit-bildanalyse' => $common + [
        'title' => 'Deutungsbild zu Tiefenzeit beschreiben und interpretieren',
        'operator' => 'beschreiben und interpretieren',
        'afb' => 'I–II',
        'level' => 'gA/eA',
        'material' => 'Die Illustration zeigt breite erdgeschichtliche Schichten von einer glühenden jungen Erde über Ozeane und verzweigte Lebensformen bis zu einer kleinen menschlichen Silhouette. Linien und Entwicklungsbahnen laufen optisch auf den Menschen zu. Das ist ein Deutungsbild für Kontingenz und Tiefenzeit, keine maßstabsgetreue Evolutionsgrafik und kein Beweis einer zielgerichteten Evolution.',
        'criteria' => ['Beschreibung strikt vor Interpretation', 'Bildaufbau, Symmetrie oder Asymmetrie und Bildschwerpunkt', 'Farben, Objekte, Linien, Muster und Kontraste', 'Entwicklungsstufen und auf den Menschen zulaufende Linien gedeutet', 'mögliche Zielgerichtetheit als Bildwirkung erkannt und fachlich kritisch begrenzt'],
        'minimum_chars' => 280,
    ],
    'menschwerdung-kontingenz' => $common + [
        'title' => 'Voraussetzungen und Kontingenz der Menschwerdung einordnen',
        'operator' => 'herausarbeiten und einordnen',
        'afb' => 'I–II',
        'level' => 'gA/eA',
        'material' => 'Der Lesetext behandelt Planetenentstehung und Mond, frühes Leben, Sauerstoffanreicherung, Massenaussterben, verzweigte Homininenevolution, symbolische Kultur sowie technische Beschleunigung. Zu unterscheiden sind notwendige Bedingungen, kontingente Wendepunkte und langfristige Prozesse.',
        'criteria' => ['mindestens sechs sachlich zutreffende Stationen', 'unterschiedliche Zeitskalen', 'Bedingung, Wendepunkt und Prozess begrifflich unterschieden', 'jede Zuordnung kurz begründet', 'keine zielgerichtete Evolutionsleiter unterstellt'],
        'minimum_chars' => 300,
    ],
    'perspektiven-synthese' => $common + [
        'title' => 'Perspektiven auf den Menschen zu einer These verbinden',
        'operator' => 'vergleichen und eine These entwickeln',
        'afb' => 'II–III',
        'level' => 'gA/eA',
        'material' => 'Die Materialien erschließen Tiefenzeit und Kontingenz, kosmische Maßstäbe, technische Macht und Verantwortung, weltweite Ritualkultur sowie Verkörperung und Sozialität. Die Synthese soll Teilperspektiven verbinden, ohne Unterschiede ihrer Aussageebenen einzuebnen.',
        'criteria' => ['mindestens drei Perspektiven konkret einbezogen', 'Ergänzungen und ein echter Konflikt unterschieden', 'Aussageebenen nicht vermischt', 'offene Frage benannt', 'prägnante begründete These statt Aufzählung'],
        'minimum_chars' => 320,
    ],
    'bewusstsein-bildanalyse' => $common + [
        'title' => 'Illustration zum Erkenntnisproblem des Bewusstseins analysieren',
        'operator' => 'beschreiben und interpretieren',
        'afb' => 'I–II',
        'level' => 'gA/eA',
        'material' => 'Die Illustration stellt ein menschliches und ein künstliches Profil einander gegenüber. Im menschlichen Profil erscheinen Erinnerungs-, Gefühls- und Erlebensmotive; das künstliche Profil zeigt ein komplexes Netz mit offenem dunklem Zentrum. Das Bild visualisiert eine epistemische Asymmetrie, beweist aber weder menschliches noch künstliches Innenleben.',
        'criteria' => ['Beschreibung vor Deutung', 'Komposition, Blickrichtung und Gegenüberstellung', 'Farbe, Licht, Formen, Netz und offenes Zentrum', 'Erkenntnisproblem statt vorschnellem Ergebnis', 'Grenzen einer KI-Illustration reflektiert'],
        'minimum_chars' => 240,
    ],
    'wuerde-rechte-bildanalyse' => $common + [
        'title' => 'Illustration zu Würde, Schutz und Verantwortung analysieren',
        'operator' => 'beschreiben und interpretieren',
        'afb' => 'I–II',
        'level' => 'gA/eA',
        'material' => 'Die Illustration ordnet menschliche Figuren, eine künstliche Gestalt, Lichtzonen, eine Schwelle und eine menschliche Hand in einem gemeinsamen Raum an. Eine tragfähige Interpretation unterscheidet gleichen menschlichen Würdestatus, einen erst zu begründenden möglichen KI-Schutz und menschliche Verantwortung, ohne diese Aussage bereits in die Beschreibung einzutragen.',
        'criteria' => ['Beschreibung konsequent vor Interpretation', 'Raumaufteilung, Größenverhältnisse und Figurenanordnung', 'Licht, Farben, Schwellen, Blickrichtungen und Kontraste', 'Menschenwürde, möglicher KI-Schutz und Verantwortung differenziert gedeutet', 'Offenheit und Grenze des Bildes ausdrücklich benannt'],
        'minimum_chars' => 260,
    ],
    'bewusstsein-modelle-vergleichen' => $common + [
        'title' => 'Bewusstseinsmodelle vergleichen und auf KI beziehen',
        'operator' => 'vergleichen und beurteilen',
        'afb' => 'II–III',
        'level' => 'gA/eA',
        'material' => 'Die Dokumentation stellt unter anderem Filtertheorie, Panpsychismus, Integrated Information Theory und Positionen von Anil Seth und David Chalmers zur KI-Frage gegenüber. Ein tragfähiger Vergleich unterscheidet Grundannahme, Erklärungsgewinn, empirische Reichweite und offene Schwierigkeit.',
        'criteria' => ['zwei Modelle anhand gleicher Kriterien verglichen', 'Grundannahme und Erklärungsgewinn', 'offene Schwierigkeit oder theoretischer Preis', 'Seth und Chalmers sachgerecht unterschieden', 'vorläufiges KI-Urteil mit Gegenargument'],
        'minimum_chars' => 420,
    ],
    'plessner-zusammenfassen' => $common + [
        'title' => 'Plessners Menschenbild zusammenfassen',
        'operator' => 'zusammenfassen',
        'afb' => 'I',
        'level' => 'gA/eA',
        'material' => 'Plessners philosophische Anthropologie bestimmt den Menschen über seine exzentrische Positionalität: Er ist Leib und hat zugleich seinen Körper, erlebt sich aus einer Mitte und kann sich zu sich selbst in Distanz setzen. Daraus folgen natürliche Künstlichkeit, vermittelte Unmittelbarkeit und utopischer Standort.',
        'criteria' => ['konkrete Wiedergabe des Gedankengangs', 'Leibsein und Körperhaben', 'exzentrische Positionalität', 'Folgen für Selbstverhältnis und Lebensführung', 'keine bloße Stichwortliste'],
    ],
    'plessner-analysieren' => $common + [
        'title' => 'Plessners Argumentation analysieren',
        'operator' => 'analysieren',
        'afb' => 'II',
        'level' => 'gA/eA',
        'material' => 'Plessner verbindet biologische Organisationsform und philosophische Deutung. Die Begriffe Grenze, Positionalität und Exzentrizität bauen aufeinander auf und erklären, warum der Mensch sich selbst zum Gegenstand werden kann.',
        'criteria' => ['Begriffsbeziehungen rekonstruieren', 'Argumentfunktion statt Definitionen auflisten', 'Textbelege', 'Folgerungen aus der Exzentrizität', 'präzise Fachsprache'],
    ],
    'plessner-erlaeutern' => $common + [
        'title' => 'Plessners Ansatz an einem Beispiel erläutern',
        'operator' => 'erläutern',
        'afb' => 'II',
        'level' => 'gA/eA',
        'material' => 'Eine Erläuterung verbindet Fachbegriff, konkretes Beispiel und Rückbindung. Der Mensch kann spontan handeln und sich zugleich beobachten, soziale Rollen übernehmen und zu ihnen Stellung nehmen.',
        'criteria' => ['zutreffender Fachbegriff', 'anschauliches, nicht triviales Beispiel', 'nachvollziehbare Zuordnung jedes Beispielteils', 'Rückbindung an Plessners These'],
    ],
    'scheler-analysieren' => $common + [
        'title' => 'Schelers Geistbegriff analysieren',
        'operator' => 'analysieren',
        'afb' => 'II',
        'level' => 'eA',
        'material' => 'Scheler unterscheidet den weltoffenen Geist von bloßer Umweltgebundenheit. Der Mensch kann Gegenstände sachlich erfassen, Triebimpulse hemmen und sich selbst zum Gegenstand machen.',
        'criteria' => ['Argumentationsschritte', 'Umweltgebundenheit und Weltoffenheit', 'Geist als Vollzug und nicht bloß Intelligenz', 'Textbelege', 'Folgerung für das Menschenbild'],
    ],
    'scheler-beurteilen' => $common + [
        'title' => 'Schelers Sonderstellungsthese beurteilen',
        'operator' => 'beurteilen',
        'afb' => 'III',
        'level' => 'eA',
        'material' => 'Schelers ontologische Sonderstellung des Menschen muss mit Befunden moderner Anthropologie und graduellen Tier-Mensch-Kontinuitäten ins Verhältnis gesetzt werden.',
        'criteria' => ['empirische und ontologische Aussage unterscheiden', 'Kriterien offenlegen', 'Gegenbefund fair einbeziehen', 'Tragweite und Grenze abwägen', 'begründetes Urteil'],
    ],
    'frankl-leid-analysieren' => $common + [
        'title' => 'Frankls Freiheit im Leiden herausarbeiten',
        'operator' => 'herausarbeiten',
        'afb' => 'II',
        'level' => 'eA',
        'material' => 'Frankl behauptet keine grenzenlose Freiheit. Wo eine Situation nicht verändert werden kann, bleibt unter Umständen eine Freiheit der Stellungnahme. Diese Aussage darf Leid weder verklären noch Betroffenen Schuld zuschieben.',
        'criteria' => ['Bedingungen und Reichweite der Einstellungsfreiheit', 'Grenze äußerer Veränderbarkeit', 'Verantwortung ohne Opferbeschuldigung', 'Textbelege', 'keine Leidensromantik'],
    ],
    'frankl-leid-beurteilen' => $common + [
        'title' => 'Frankls Leidensdeutung beurteilen',
        'operator' => 'beurteilen',
        'afb' => 'III',
        'level' => 'eA',
        'material' => 'Die Deutung wird an einem Fall geprüft. Zuerst sind Schutz, Hilfe und veränderbare Ursachen zu berücksichtigen; erst danach ist die Frage einer möglichen inneren Stellungnahme angemessen.',
        'criteria' => ['Fallbezug', 'Schutz und strukturelle Verantwortung', 'Stärke der Sinnperspektive', 'Missbrauchsgefahr', 'differenziertes Urteil'],
    ],
    'rechte-quellen' => $common + [
        'title' => 'Würdebegründungen analysieren und vergleichen',
        'operator' => 'analysieren und vergleichen',
        'afb' => 'II',
        'level' => 'gA/eA',
        'material' => 'Begründungswege können theologisch, vernunftrechtlich, politisch-rechtlich oder diskursethisch sein. Zu unterscheiden sind Träger, Grund, Verpflichtung, Geltung und Durchsetzung.',
        'criteria' => ['Träger und Begründungsgrund jeder Quelle', 'Folgen für andere', 'kriteriengeleitete Gemeinsamkeiten und Unterschiede', 'Geltung, Begründung und Durchsetzung unterscheiden', 'Textbelege'],
    ],
    'rechte-begruenden' => $common + [
        'title' => 'Universale Menschenrechte plural begründen',
        'operator' => 'erörtern',
        'afb' => 'III',
        'level' => 'gA/eA',
        'material' => 'In einer globalisierten Welt konkurrieren Weltanschauungen. Eine tragfähige Erörterung prüft, ob ein überlappender Konsens oder Begründungspluralismus universale Geltung stützen kann und wo Macht, Durchsetzung und kulturelle Konflikte Grenzen setzen.',
        'criteria' => ['stärkstes Argument des gewählten Ansatzes', 'ernsthafter Grenzfall', 'Ergänzung durch zweiten Ansatz', 'Gegenargument', 'Abwägung und Urteil'],
    ],
    'rechte-konflikt' => $common + [
        'title' => 'Menschenrechtskonflikt beurteilen',
        'operator' => 'beurteilen',
        'afb' => 'III',
        'level' => 'gA/eA',
        'material' => 'Kulturelle Vielfalt ist zu achten, endet aber dort, wo der gleiche Würdestatus und grundlegende individuelle Rechte verletzt werden. Eine vermittelnde Regel braucht Universalisierbarkeit, Verhältnismäßigkeit und Betroffenenperspektive.',
        'criteria' => ['Rechts- und Interessenkollision bestimmen', 'legitime Vielfalt von Verletzung unterscheiden', 'Kriterien anwenden', 'mögliche Einwände berücksichtigen', 'vermittelnde Regel begründen'],
    ],
    'rechte-ea' => $common + [
        'title' => 'Begründungspluralismus der Menschenrechte erörtern',
        'operator' => 'erörtern',
        'afb' => 'III',
        'level' => 'eA',
        'material' => 'Die These unterscheidet die universale Geltung der Menschenrechte von pluralen religiösen, philosophischen und politisch-rechtlichen Begründungen sowie von ihrer institutionellen Durchsetzung. Zu prüfen ist, ob ein überlappender Konsens auch in globalen Konflikten trägt.',
        'criteria' => ['Geltung, Begründung und Durchsetzung trennen', 'mindestens drei Quellen oder Begründungswege', 'Pro- und Contraargumente entfalten', 'globalen Konflikt oder Grenzfall einbeziehen', 'kriteriengeleitete Abwägung und eigenes Urteil'],
        'minimum_chars' => 420,
    ],
    'bilanz-gesamturteil' => $common + [
        'title' => 'Gesamturteil zur Frage „Was ist der Mensch?“',
        'operator' => 'beurteilen',
        'afb' => 'III',
        'level' => 'gA/eA',
        'material' => 'Die Bilanz verbindet empirischen Befund, Grenze einer Teilperspektive, einen Begriff aus der philosophischen Anthropologie, die Unterscheidung funktionalen Zugangs und phänomenalen Erlebens sowie eine Folgerung für Würde oder Rechte.',
        'criteria' => ['alle fünf geforderten Bausteine', 'stringente Verbindung statt Aufzählung', 'fachsprachliche Präzision', 'Einwand oder Grenze', 'begründetes Gesamturteil'],
        'minimum_chars' => 420,
    ],
    'abitur-ga' => $common + [
        'title' => 'Schriftliches Abiturtraining gA',
        'operator' => 'analysieren, erläutern und beurteilen',
        'afb' => 'I–III',
        'level' => 'gA',
        'material' => 'Mehrteilige Aufgabe zu Verhaltensdaten, Bewusstseinstheorie und Schutzansprüchen. Rückmeldung trennt die Teilaufgaben und prüft Materialbezug, Fachbegriffe, Argumentation und Urteil.',
        'criteria' => ['Teilaufgaben erkennbar getrennt', 'Argumentationsstruktur der These', 'Leistung und Grenze eines Bewusstseinsansatzes', 'Kriterien für Schutzstatus', 'abwägendes Schlussurteil'],
        'minimum_chars' => 600,
    ],
    'abitur-ea' => $common + [
        'title' => 'Schriftliches Abiturtraining eA',
        'operator' => 'analysieren, vergleichen und erörtern',
        'afb' => 'I–III',
        'level' => 'eA',
        'material' => 'Mehrteilige Aufgabe zum Begründungspluralismus universaler Menschenwürde. Analyse, philosophisch-theologischer Vergleich und Erörterung sind getrennt zu prüfen.',
        'criteria' => ['Voraussetzungen der These', 'kriteriengeleiteter Vergleich', 'Geltung und Begründung unterscheiden', 'Gegenargument und globaler Konflikt', 'reflektiertes Urteil'],
        'minimum_chars' => 750,
    ],
    'kolloquium' => $common + [
        'title' => 'Kolloquiumsvorbereitung',
        'operator' => 'darstellen, erläutern und beurteilen',
        'afb' => 'I–III',
        'level' => 'gA/eA',
        'material' => 'Ein tragfähiger Kurzvortrag enthält Leitthese, klaren Gedankengang, passende Fachbegriffe, Material- oder Textbezug, einen ernsthaften Einwand und ein begründetes Schlussurteil.',
        'criteria' => ['Leitthese', 'logische Gliederung in drei Schritte', 'fachliche Genauigkeit', 'Beispiel oder Textbezug', 'Einwand und Schlussurteil', 'mündlich gut vortragbare Stichpunkte'],
        'minimum_chars' => 300,
    ],
];
