<?php
declare(strict_types=1);

$common = [
    'curriculum' => 'LehrplanPLUS Bayern, Katholische Religionslehre, Jahrgangsstufe 11; Naturwissenschaft, Weltbild, Gottesfrage und Erkenntnisgrenzen; operatorengestützte kompetenzorientierte Rückmeldung',
    'minimum_chars' => 180,
    'maximum_chars' => 9000,
    'prompt_version' => 'kr11-block-c-feedback-2026-08-v1',
];

return [
    'block-c-galilei-textarbeit' => $common + [
        'title' => 'Lütz’ Darstellung des Falls Galilei erschließen und beurteilen',
        'operator' => 'zusammenfassen, analysieren und beurteilen',
        'afb' => 'I–III',
        'level' => 'Jgst. 11',
        'material' => 'Der geschützte Originalauszug aus Manfred Lütz, Gott – eine kleine Geschichte des Größten, S. 45–46, behandelt Ausgangslage, Eskalation und Folgen des Falls Galilei. Lütz deutet den Fall zugespitzt als menschliche Tragödie. Die drei Schülerfelder bilden eine zusammenhängende Textarbeit: Zuerst wird der Gedankengang sachlich zusammengefasst, anschließend das Zusammenwirken wissenschaftlicher, kirchlicher, politischer und persönlicher Faktoren analysiert und zuletzt Lütz’ These kriteriengeleitet beurteilt. Das Feedback muss die Funktionen der drei Teilantworten unterscheiden und darf fehlende Textbelege nicht erfinden.',
        'criteria' => ['Zusammenfassung konzentriert sich auf Ausgangslage, Eskalation und Folgen', 'Analyse erklärt das Zusammenwirken mehrerer Faktoren mit Textbezug', 'Lütz’ Autorenposition wird von der eigenen Deutung getrennt', 'Beurteilung legt Kriterien offen und berücksichtigt einen Einwand', 'abschließendes Urteil ist abwägend und am Material begründet'],
        'minimum_chars' => 700,
    ],
    'block-c-berechenbarkeit-unterscheiden' => $common + [
        'title' => 'Drei Ebenen der Berechenbarkeit unterscheiden',
        'operator' => 'unterscheiden und erläutern',
        'afb' => 'II',
        'level' => 'Jgst. 11',
        'material' => 'Zu trennen sind Naturgesetzlichkeit beziehungsweise grundsätzliche Modellierbarkeit, praktische Vorhersagbarkeit und Sinn- oder Bedeutungsfragen. Ein deterministisches Modell kann wegen Komplexität, chaotischer Dynamik oder fehlender Daten praktisch unvorhersagbar sein. Aus einer vollständigen Funktionsbeschreibung folgt nicht automatisch eine Antwort auf Bedeutung, Wert oder Zweck.',
        'criteria' => ['alle drei Ebenen klar unterscheiden', 'Naturgesetzlichkeit nicht mit praktischer Berechenbarkeit gleichsetzen', 'plausibles Beispiel oder Grenze', 'Sinnfrage nicht als bloße Rechenlücke darstellen', 'Beziehungen der Ebenen erklären'],
    ],
    'block-c-galilei-zusammenfassen' => $common + [
        'title' => 'Lütz’ Darstellung des Falls Galilei prägnant zusammenfassen',
        'operator' => 'zusammenfassen',
        'afb' => 'I',
        'level' => 'Jgst. 11',
        'material' => 'Der im geschützten Lernraum gelesene Auszug von Manfred Lütz behandelt die wissenschaftliche und kirchenpolitische Ausgangslage, die Eskalation des Konflikts um Galilei, Verurteilung und Hausarrest sowie die spätere Symbol- und Wirkungsgeschichte. Lütz deutet den Fall zugespitzt als menschliche Tragödie. Das Feedback muss sich auf die im Schülertext erkennbar verarbeiteten Aussagen dieses Auszugs beschränken.',
        'criteria' => ['konkreter Inhalt statt bloßer Themenangabe', 'Ausgangslage, Eskalation und Folgen in einem Gedankengang', 'Lütz’ Deutung als Autorenposition kenntlich machen', 'sachlich, prägnant und in eigenen Worten', 'keine Bewertung in der Zusammenfassung'],
        'minimum_chars' => 260,
    ],
    'block-c-galilei-analysieren' => $common + [
        'title' => 'Die Eskalation des Galilei-Konflikts analysieren',
        'operator' => 'analysieren',
        'afb' => 'II',
        'level' => 'Jgst. 11',
        'material' => 'Nach Lütz wirken wissenschaftliche Modellkonflikte, konfessionelle Spannung, kirchliche Kontrollinteressen, die Vereinbarung von 1616, Galileis Auftreten, die Publikation des italienischen Dialogs, die Figur Simplicio, persönliche Kränkung und institutionelle Macht im zweiten Prozess zusammen. Die Analyse soll Faktoren, Beziehungen und Funktion in Lütz’ Darstellung untersuchen, nicht nur Ereignisse aufzählen.',
        'criteria' => ['wissenschaftliche, kirchliche, politische und persönliche Faktoren unterscheiden', 'Zusammenwirken und Eskalationslogik erklären', 'mindestens zwei konkrete Textbezüge', 'Autorendarstellung von eigener Deutung trennen', 'keine monokausale Formel Kirche gegen Wissenschaft'],
        'minimum_chars' => 280,
    ],
    'block-c-galilei-beurteilen' => $common + [
        'title' => 'Lütz’ These von der menschlichen Tragödie beurteilen',
        'operator' => 'beurteilen',
        'afb' => 'III',
        'level' => 'Jgst. 11',
        'material' => 'Lütz’ Formulierung „vor allem eine menschliche Tragödie“ gewichtet persönliche Kommunikation, Kränkung und Fehlentscheidungen stark. Ein Urteil muss prüfen, wie viel diese Deutung erklärt und ob sie institutionelle, theologische, politische und wissenschaftshistorische Faktoren angemessen berücksichtigt. Zustimmung, Ablehnung und abgestufte Urteile sind möglich.',
        'criteria' => ['Urteilskriterien offenlegen', 'These am Text prüfen', 'Erklärungskraft persönlicher Faktoren bestimmen', 'institutionelle oder wissenschaftshistorische Gegenperspektive berücksichtigen', 'abwägendes Urteil; nicht die gewünschte Schlussposition bewerten'],
        'minimum_chars' => 300,
    ],
    'block-c-weltmaschine-pruefen' => $common + [
        'title' => 'Die Weltmaschinen-Idee an einem Beispiel prüfen',
        'operator' => 'prüfen und erläutern',
        'afb' => 'II',
        'level' => 'Jgst. 11',
        'material' => 'An Wetter, Würfelwurf, menschlicher Entscheidung oder Planetenbahn werden drei Ebenen geprüft: gesetzmäßige Beschreibbarkeit, praktische Vorhersagbarkeit und sinnbezogene Deutung. Physikalische Gesetzmäßigkeit garantiert keine praktisch exakte Prognose und entscheidet keine Sinnfrage.',
        'criteria' => ['konkretes Beispiel konsequent durchführen', 'gesetzmäßige Beschreibung sachlich plausibel', 'praktische Vorhersagegrenzen erklären', 'Sinn- oder Bedeutungsfrage klar abgrenzen', 'keine Kategorienverwechslung'],
    ],
    'block-c-nietzsche-deuten' => $common + [
        'title' => 'Nietzsches Satz „Gott ist tot“ deuten',
        'operator' => 'deuten',
        'afb' => 'II',
        'level' => 'Jgst. 11',
        'material' => 'Im Aphorismus 125 der Fröhlichen Wissenschaft beschreibt der tolle Mensch nicht den biologischen Tod eines göttlichen Wesens. Diagnostiziert wird der Verlust selbstverständlicher Geltung des christlich-metaphysischen Horizonts. Damit geraten Sinn und moralische Gewissheiten ins Wanken; Menschen müssen Verantwortung für neue Wertsetzungen übernehmen. Naturwissenschaft allein beweist oder widerlegt Gott nicht.',
        'criteria' => ['metaphorische kulturdiagnostische Bedeutung', 'Gefahr des Orientierungs- und Werteverlusts', 'neue menschliche Verantwortung', 'mechanistisches Weltbild passend einordnen', 'keinen naturwissenschaftlichen Gottesbeweis oder Gegenbeweis behaupten'],
    ],
    'block-c-naturalismus-beurteilen' => $common + [
        'title' => 'Vom methodischen Naturalismus auf Gottes Nichtexistenz schließen?',
        'operator' => 'beurteilen',
        'afb' => 'III',
        'level' => 'Jgst. 11',
        'material' => 'Methodischer Naturalismus ist die wissenschaftliche Arbeitsregel, Naturvorgänge mit natürlichen, überprüfbaren Ursachen zu erklären. Ontologischer Naturalismus ist die weitergehende philosophische These, dass nur Naturwirklichkeit existiert. Dass eine naturwissenschaftliche Erklärung die Zusatzannahme Gott nicht benötigt, beweist für sich allein weder Gottes Existenz noch Nichtexistenz.',
        'criteria' => ['methodisch und ontologisch präzise unterscheiden', 'Gültigkeitskriterium für den Schluss offenlegen', 'verborgene Zusatzprämisse erkennen', 'starkes Pro- oder Contraargument berücksichtigen', 'begründetes Urteil ohne persönliche Glaubensposition'],
    ],
    'block-c-perspektiven-unterscheiden' => $common + [
        'title' => 'Widerspruch und Perspektivendifferenz unterscheiden',
        'operator' => 'unterscheiden und erläutern',
        'afb' => 'II',
        'level' => 'Jgst. 11',
        'material' => 'Verschiedene Projektionen desselben räumlichen Gegenstands können ringförmig beziehungsweise rechteckig erscheinen, ohne sich logisch zu widersprechen, wenn Blickrichtung und Aussagebereich verschieden sind. Ein echter Widerspruch liegt vor, wenn über denselben Gegenstand im selben Sinn zugleich Unvereinbares behauptet wird. Falsche Beschreibungen zeigen sich durch verfehlten Gegenstandsbezug, unpassende Perspektive, innere Inkonsistenz oder Scheitern an gemeinsamer Prüfung.',
        'criteria' => ['selber Gegenstand, Hinsicht und Zeitpunkt als Widerspruchsbedingungen', 'Perspektivendifferenz klar erklären', 'Projektionsmodell passend verwenden', 'mindestens ein belastbares Prüfkriterium', 'nicht jede Differenz vorschnell harmonisieren'],
    ],
    'block-c-mara-beurteilen' => $common + [
        'title' => 'Die Begründungsqualität in Maras Entscheidung beurteilen',
        'operator' => 'analysieren und beurteilen',
        'afb' => 'II–III',
        'level' => 'Jgst. 11',
        'material' => 'Naturwissenschaft und Psychologie können Risiken, Folgen, Belastungen und Einflussfaktoren untersuchen. Eine christlich-religiöse Perspektive kann Berufung, Verantwortung, Gewissen, Nächstenliebe, Freiheit und Gebet als Deutungshorizont einbringen. Philosophie prüft Gründe, Pflichten, Ziele, Werte und Verallgemeinerbarkeit. Keine Perspektive nimmt Mara die konkrete Entscheidung ab.',
        'criteria' => ['Beiträge der drei Perspektiven trennscharf analysieren', 'christliche Deutung fachlich statt als persönliche Bekenntnispflicht darstellen', 'Reichweite und Grenze jeder Perspektive', 'Kriterien einer verantworteten Entscheidung nennen', 'nicht Maras konkrete Wahl, sondern Qualität ihrer möglichen Begründung beurteilen'],
        'minimum_chars' => 300,
    ],
    'block-c-leitfrage-eroertern' => $common + [
        'title' => 'Folgerungen naturwissenschaftlicher Erklärungen für die Gottesfrage erörtern',
        'operator' => 'erörtern',
        'afb' => 'III',
        'level' => 'Jgst. 11',
        'material' => 'Naturwissenschaftliche Erklärungen machen viele natürliche Vorgänge ohne religiöse Zusatzannahmen modellierbar. Historisch fördert dies mechanistische und naturalistische Weltbilder. Moderne Physik begrenzt klassische Vorhersagevorstellungen, liefert aber weder einen Gottesbeweis noch eine Gotteswiderlegung. Methodischer und ontologischer Naturalismus sowie empirische Erklärung und metaphysische Deutung müssen unterschieden werden.',
        'criteria' => ['methodischen und ontologischen Naturalismus unterscheiden', 'mindestens zwei Lernwegstationen sachgerecht einbeziehen', 'zulässige und unzulässige Folgerungen trennen', 'ernsthaftes Gegenargument prüfen', 'abwägendes Sachurteil ohne persönliche Glaubensaussage'],
        'minimum_chars' => 420,
    ],
];
