<?php
declare(strict_types=1);

return [
    'kr11-block-d-gott-warum-das-leid' => [
        'label' => 'KR 11 · Block D: Gott, warum das Leid?',
        'description' => 'Leiderfahrung, Theodizee, Antwortversuche und christliche Hoffnung',
        'public_url' => '/bereiche/religion-11/block-d-gott-warum-das-leid.html',
        'teacher_url' => '/bereiche/religion-11/block-d-gott-warum-das-leid/lehrer/',
        'beamer_url' => '/bereiche/religion-11/block-d-gott-warum-das-leid/beamer/',
        'status' => 'active',
    ],
    'kr13-1-2-ethik-der-lebensbereiche' => [
        'label' => 'KR 13.1.2 · Ethik der Lebensbereiche',
        'description' => 'Beziehung, Ehe und Sakrament, Sozialprinzipien, Armut, Nachhaltigkeit und Digitalisierung',
        'public_url' => '/bereiche/religion-13/ethik-der-lebensbereiche/index.html',
        'teacher_url' => '/bereiche/religion-13/ethik-der-lebensbereiche/lehrer/',
        'beamer_url' => '/bereiche/religion-13/ethik-der-lebensbereiche/beamer.html',
        'status' => 'active',
    ],
    'musik-10-spannung' => [
        'label' => 'Musik 10 · Wie entsteht musikalische Spannung?',
        'description' => 'Fachübergreifendes Startermodul der LernHTML-Architektur',
        'public_url' => '/bereiche/musik-10/spannung/',
        'teacher_url' => '/bereiche/musik-10/spannung/lehrer/',
        'beamer_url' => '/bereiche/musik-10/spannung/beamer.html',
        'status' => 'hidden',
    ],
    'musik8-rock-pop' => [
        'label' => 'Musik 8 · Rock-/Pop-Musik',
        'description' => 'Sound, Klanggeschichte, Songform, Bühne und Jugendkultur',
        'public_url' => '/musikunterricht/8/rock-pop-musik/',
        'teacher_url' => '/musikunterricht/8/rock-pop-musik/lehrer/',
        'beamer_url' => '/musikunterricht/8/rock-pop-musik/beamer/',
        'status' => 'active',
    ],
    'kr11-einstieg-gott-und-wirklichkeit' => [
        'label' => 'KR 11 · Auftakt: Gott und Wirklichkeit',
        'description' => 'Gottesverborgenheit, Wunschprojektion, Offenbarung sowie Leid und Hoffnung',
        'public_url' => '/bereiche/religion-11/einstieg-gott-und-wirklichkeit.html',
        'teacher_url' => '/bereiche/religion-11/einstieg-gott-und-wirklichkeit/lehrer/',
        'beamer_url' => '/bereiche/religion-11/einstieg-gott-und-wirklichkeit/beamer/',
        'status' => 'active',
    ],
    'kr11-block-a-wahrnehmung-und-wirklichkeit' => [
        'label' => 'KR 11 · Block A: Wahrnehmung und Wirklichkeit',
        'description' => 'Wahrnehmungsfilter, Erkenntnisprüfung und antike Denkwege',
        'public_url' => '/bereiche/religion-11/block-a-wahrnehmung-und-wirklichkeit.html',
        'teacher_url' => '/bereiche/religion-11/block-a-wahrnehmung-und-wirklichkeit/lehrer/',
        'beamer_url' => '/bereiche/religion-11/block-a-wahrnehmung-und-wirklichkeit/beamer/',
        'status' => 'active',
    ],
    'kr11-block-b-aristoteles-kommt-zurueck' => [
        'label' => 'KR 11 · Block B: Aristoteles kommt zurück',
        'description' => 'Wissensüberlieferung, Scholastik, Anselm, Thomas und Ockham',
        'public_url' => '/bereiche/religion-11/block-b-aristoteles-kommt-zurueck.html',
        'teacher_url' => '/bereiche/religion-11/block-b-aristoteles-kommt-zurueck/lehrer/',
        'beamer_url' => '/bereiche/religion-11/block-b-aristoteles-kommt-zurueck/beamer/',
        'status' => 'active',
    ],
    'kr11-block-c-die-entzauberte-welt' => [
        'label' => 'KR 11 · Block C: Die entzauberte Welt?',
        'description' => 'Naturwissenschaft, Weltmaschine, Naturalismus, Nietzsche und Erkenntnisgrenzen',
        'public_url' => '/bereiche/religion-11/block-c-die-entzauberte-welt.html',
        'teacher_url' => '/bereiche/religion-11/block-c-die-entzauberte-welt/lehrer/',
        'beamer_url' => '/bereiche/religion-11/block-c-die-entzauberte-welt/beamer/',
        'status' => 'active',
    ],
    'kr12-12.1.1-wer-bin-ich' => [
        'label' => 'KR 12.1.1 · Wer bin ich?',
        'description' => 'Anthropologie, Bewusstsein, Menschenwürde und Menschenrechte',
        'public_url' => '/bereiche/religion-12/12.1.1/',
        'teacher_url' => '/bereiche/religion-12/12.1.1/lehrer/',
        'beamer_url' => '/bereiche/religion-12/12.1.1/beamer.html',
        'status' => 'active',
    ],
    'kr13-1-1-ethische-grundlegung' => [
        'label' => 'KR 13.1.1 · Ethische Grundlegung',
        'description' => 'Ethische Urteilsbildung mit Terror, Kant, Utilitarismus, biblischen Weisungen und Gewissen',
        'public_url' => '/bereiche/religion-13/ethische-grundlegung/index.html',
        'teacher_url' => '/bereiche/religion-13/ethische-grundlegung/lehrer/',
        'beamer_url' => '/bereiche/religion-13/ethische-grundlegung/beamer.html',
        'status' => 'active',
    ],
];
