(function(){
  "use strict";
  var config=window.RELIGION_CLASSROOM_CONFIG||{},view=String(config.view||window.RELIGION_VIEW||"student"),endpoint=String(config.feedbackEndpoint||"");
  if(view!=="student"||!endpoint||!window.fetch)return;
  var widgets=[],availabilityCache=new Map(),clientId=readClientId(),room="";
  function readClientId(){var key="religion-feedback-client-v1",value="";try{value=localStorage.getItem(key)||"";}catch(e){}if(!/^[a-zA-Z0-9_-]{20,80}$/.test(value)){var bytes=new Uint8Array(18);crypto.getRandomValues(bytes);value=Array.from(bytes,function(b){return b.toString(16).padStart(2,"0");}).join("");try{localStorage.setItem(key,value);}catch(e){}}return value;}
  function api(action,data){return fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json"},credentials:"same-origin",cache:"no-store",body:JSON.stringify(Object.assign({action:action},data||{}))}).then(function(response){return response.json().catch(function(){return{ok:false,message:"Der Server hat keine lesbare Antwort geliefert."};}).then(function(payload){if(!response.ok||!payload.ok){var error=new Error(payload.message||"KI-Feedback ist momentan nicht verfügbar.");error.status=response.status;throw error;}return payload;});});}
  function textLength(value){return String(value||"").trim().length;}
  function roomCode(){try{if(window.RELIGION_CLASSROOM&&typeof window.RELIGION_CLASSROOM.room==="function")return String(window.RELIGION_CLASSROOM.room()||"");}catch(e){}return room;}
  function safeList(values){return Array.isArray(values)?values.map(function(value){return String(value||"").trim();}).filter(Boolean):[];}
  function renderFeedback(target,payload){var feedback=payload.feedback||{};target.innerHTML="";var title=document.createElement("h4");title.textContent="Dein formatives KI-Feedback";target.appendChild(title);var overall=document.createElement("p");overall.textContent=String(feedback.overall||"");target.appendChild(overall);[["Das gelingt bereits",safeList(feedback.strengths)],["Nächste Überarbeitungsschritte",safeList(feedback.next_steps)]].forEach(function(group){var heading=document.createElement("h5");heading.textContent=group[0];target.appendChild(heading);var list=document.createElement("ul");group[1].forEach(function(value){var item=document.createElement("li");item.textContent=value;list.appendChild(item);});target.appendChild(list);});[["Operator",feedback.operator_check],["Fachlichkeit",feedback.subject_check],["Überarbeitungsimpuls",feedback.revision_prompt]].forEach(function(row){var p=document.createElement("p"),strong=document.createElement("strong");strong.textContent=row[0]+": ";p.appendChild(strong);p.appendChild(document.createTextNode(String(row[1]||"")));target.appendChild(p);});if(feedback.privacy_note){var privacy=document.createElement("p");privacy.className="ai-feedback-privacy";privacy.textContent=String(feedback.privacy_note);target.appendChild(privacy);}var notice=document.createElement("small");notice.textContent=String(payload.notice||"Formative Überarbeitungshilfe – keine Note.");target.appendChild(notice);target.hidden=false;}
  function setState(widget,message,error){widget.status.textContent=message||"";widget.status.classList.toggle("error",Boolean(error));}
  function updateButton(widget){var code=roomCode(),length=textLength(widget.input.value),minimum=Number(widget.availability&&widget.availability.minimumChars||180);widget.count.textContent=length+" Zeichen";if(!code){widget.button.disabled=true;setState(widget,"Verbinde dich zuerst mit dem Klassenraum.");return;}if(!widget.availability||!widget.availability.available){widget.button.disabled=true;setState(widget,widget.availability&&widget.availability.reason||"Verfügbarkeit wird geprüft …");return;}if(length<minimum){widget.button.disabled=true;setState(widget,"Noch "+(minimum-length)+" Zeichen bis zu einer hinreichend ausgearbeiteten Lösung.");return;}widget.button.disabled=false;setState(widget,"Feedback prüft Operator "+widget.availability.operator+" · AFB "+widget.availability.afb+".");}
  function checkAvailability(widget,force){var code=roomCode();if(!code){widget.availability=null;updateButton(widget);return Promise.resolve();}var key=code+"|"+widget.taskId,cached=availabilityCache.get(key);if(!force&&cached&&Date.now()-cached.at<30000){widget.availability=cached.value;updateButton(widget);return Promise.resolve();}return api("availability",{room:code,taskId:widget.taskId}).then(function(data){widget.availability=data;availabilityCache.set(key,{at:Date.now(),value:data});updateButton(widget);}).catch(function(error){widget.availability={available:false,reason:error.message};updateButton(widget);});}
  function buildWidget(host,index){var input=host.querySelector("textarea,input[type='text']");if(!input)return;var taskId=String(host.dataset.feedbackTask||"");if(!taskId)return;var panel=document.createElement("section");panel.className="ai-feedback-widget";panel.setAttribute("aria-labelledby","ai-feedback-title-"+index);panel.innerHTML='<div class="ai-feedback-head"><div><p class="live-inline-eyebrow">Optionale Überarbeitungshilfe</p><h4 id="ai-feedback-title-'+index+'">KI-Feedback zur eigenen Lösung</h4></div><span data-feedback-count>0 Zeichen</span></div><p>Erst selbst lösen, dann gezielt überarbeiten. Bitte keine Namen oder sensiblen persönlichen Angaben eingeben. <a href="/datenschutz-lernplattform/" target="_blank" rel="noopener noreferrer">Was wird übertragen?</a></p><button class="live-btn" type="button" data-feedback-generate disabled>KI-Feedback generieren</button><p class="live-status" data-feedback-status role="status" aria-live="polite"></p><div class="ai-feedback-result" data-feedback-result hidden></div>';
    host.appendChild(panel);var widget={host:host,input:input,taskId:taskId,panel:panel,button:panel.querySelector("[data-feedback-generate]"),status:panel.querySelector("[data-feedback-status]"),count:panel.querySelector("[data-feedback-count]"),result:panel.querySelector("[data-feedback-result]"),availability:null};
    input.addEventListener("input",function(){updateButton(widget);});widget.button.addEventListener("click",function(){var code=roomCode();widget.button.disabled=true;widget.result.hidden=true;setState(widget,"Feedback wird erzeugt …");api("generate",{room:code,taskId:taskId,answer:input.value,clientId:clientId}).then(function(data){renderFeedback(widget.result,data);setState(widget,"Rückmeldung bereit. Überarbeite nun gezielt deinen Text.");updateButton(widget);}).catch(function(error){setState(widget,error.message,true);updateButton(widget);});});widgets.push(widget);checkAvailability(widget,false);}
  document.querySelectorAll("[data-feedback-task]").forEach(buildWidget);
  document.addEventListener("religion-classroom-state",function(event){var next=String(event.detail&&event.detail.room||"");if(next!==room){room=next;widgets.forEach(function(widget){widget.availability=null;checkAvailability(widget,true);});}});
  setInterval(function(){widgets.forEach(function(widget){checkAvailability(widget,false);});},30000);
})();
