<?php
declare(strict_types=1);
require_once getenv('TEACHER_PLATFORM_BOOTSTRAP') ?: '/websites/_protected/teacher-platform-v1/app/bootstrap.php';
use ReligionPlatform\Auth;
use ReligionPlatform\Identity;
use ReligionPlatform\Modules;
use ReligionPlatform\Portal;
use ReligionPlatform\SchoolDirectory;
use ReligionPlatform\Security;

Security::headers("default-src 'self'; img-src 'self' data:; style-src 'self'; script-src 'none'; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'");
Security::startSession();
$error='';
if(($_SERVER['REQUEST_METHOD'] ?? 'GET')==='POST') {
    try {header('Location: '.Portal::action($_POST,$_FILES),true,303);exit;}
    catch(Throwable $exception) {
        $error=$exception instanceof PDOException?'Die Angaben konnten nicht gespeichert werden. Bitte Anmeldename und Listennummer auf doppelte Einträge prüfen.':$exception->getMessage();
    }
}
$identity=Identity::current();
$teacher=$identity && $identity['kind']==='teacher'?Auth::currentUser(null):null;
$admin=$identity && $identity['role']==='admin';
$next=Portal::next($_GET['next'] ?? $_POST['next'] ?? null);
$personal=(string)($_GET['person'] ?? '');
if(preg_match('/^[a-f0-9]{32}$/D',$personal)) {
    $q=ReligionPlatform\Database::connection()->prepare('SELECT l.username,o.slug FROM platform_learners l JOIN organisations o ON o.id=l.organisation_id WHERE l.subject=? AND o.status="active"');
    $q->execute([$personal]);
    if($prefill=$q->fetch()) {$_GET['schule']=$prefill['slug'];$_GET['u']=$prefill['username'];}
}
$view=(string)($_GET['view'] ?? 'home');
$once=$_SESSION['shared_portal_once'] ?? [];unset($_SESSION['shared_portal_once']);
$rosterCredentials=$_SESSION['shared_roster_credentials'] ?? [];unset($_SESSION['shared_roster_credentials']);
$pendingRoster=$_SESSION['shared_roster_preview'] ?? null;
$previewToken=(string)($_GET['roster_preview'] ?? '');
if(!is_array($pendingRoster) || ($pendingRoster['expires_at'] ?? 0)<time() || !$previewToken || !hash_equals((string)($pendingRoster['token'] ?? ''),$previewToken)) $pendingRoster=null;
$h=static fn($v)=>Security::h((string)$v);
function fields(string $action): void {echo '<input type="hidden" name="csrf" value="'.Security::h(Security::csrf()).'"><input type="hidden" name="action" value="'.Security::h($action).'">';}
?>
<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mein Unterricht · LernHTML und Prüfungsapp</title><link rel="stylesheet" href="/lehrer/assets/platform.css"><link rel="stylesheet" href="/zugang/portal.css"></head><body>
<header class="app-header"><a class="brand" href="/zugang/">Mein Unterricht</a><?php if($identity): ?><div class="account"><span><?= $h($identity['display_name']) ?></span><form method="post" class="logout-form"><?php fields('logout'); ?><button class="text-button">Abmelden</button></form></div><?php endif; ?></header>
<main class="portal-content">
<?php if($error): ?><p class="alert error" role="alert"><?= $h($error) ?></p><?php endif; ?>
<?php if($once): ?><section class="panel one-time"><h2>Zugang eingerichtet</h2><p>Diese Zugangsdaten werden nur jetzt angezeigt. Bewahre sie sicher auf.</p><dl><?php foreach($once as $key=>$value): ?><dt><?= $h(['start_password'=>'Startpasswort','url'=>'Persönlicher Einstieg','username'=>'Anmeldename','client_id'=>'Installationskennung','client_secret'=>'Verbindungsschlüssel','issuer'=>'Anmeldeanbieter','subject'=>'Personenkennung'][$key] ?? $key) ?></dt><dd><code><?= $h($value) ?></code></dd><?php endforeach; ?></dl></section><?php endif; ?>
<?php if($rosterCredentials): ?><section class="panel one-time"><h2><?= count($rosterCredentials) ?> neue Schülerzugänge</h2><p>Die Startpasswörter werden nur jetzt angezeigt. Bitte sicher ausgeben oder ausdrucken.</p><div class="table-wrap"><table><thead><tr><th>Anmeldename</th><th>Startpasswort</th><th>Persönlicher Einstieg</th></tr></thead><tbody><?php foreach($rosterCredentials as $credential): ?><tr><td><code><?= $h($credential['username']) ?></code></td><td><code><?= $h($credential['start_password']) ?></code></td><td><small><?= $h($credential['url']) ?></small></td></tr><?php endforeach; ?></tbody></table></div></section><?php endif; ?>
<?php if(!$identity): ?>
<section class="hero"><p class="eyebrow">LernHTML und Prüfungsapp</p><h1>Ein Zugang für deinen Unterricht.</h1><p>Hier findest du die Angebote, die für dich freigegeben sind.</p></section>
<div class="two-col portal-section"><section class="panel"><h2>Schülerinnen und Schüler</h2><form method="post"><?php fields('student_login'); ?><input type="hidden" name="next" value="<?= $h($next) ?>"><label>Schulkürzel<input name="school" autocomplete="organization" value="<?= $h($_GET['schule'] ?? $_POST['school'] ?? '') ?>" required></label><label>Anmeldename<input name="username" autocomplete="username" value="<?= $h($_GET['u'] ?? '') ?>" required></label><label>Passwort<input name="password" type="password" autocomplete="current-password" required></label><button class="primary">Anmelden</button></form><p><small>Dein persönlicher Link füllt Schule und Anmeldenamen aus. Das Startpasswort erhältst du von deiner Lehrkraft.</small></p></section>
<section class="panel"><h2>Lehrkräfte</h2><form method="post"><?php fields('teacher_login'); ?><input type="hidden" name="next" value="<?= $h($next) ?>"><label>Anmeldename oder E-Mail<input name="username" autocomplete="username" required></label><label>Passwort<input type="password" name="password" autocomplete="current-password" required></label><label>Bestätigungscode <small>falls Zwei-Faktor-Anmeldung aktiv ist</small><input name="mfa_code" autocomplete="one-time-code"></label><button class="primary">Anmelden</button></form><div class="auth-links"><a href="/lehrer/?forgot=1">Passwort vergessen</a><a href="/zugriff-anfragen/">Zugang anfragen</a></div></section></div>
<?php elseif(!empty($identity['must_change_password'])): ?>
<section class="auth-card"><h1>Dein eigenes Passwort</h1><p>Ersetze zuerst das Startpasswort. Ein gut merkbarer Satz mit mindestens 15 Zeichen eignet sich dafür.</p><form method="post"><?php fields('student_password'); ?><input type="hidden" name="next" value="<?= $h($next) ?>"><label>Startpasswort<input type="password" name="current" autocomplete="current-password" required></label><label>Neues Passwort<input type="password" name="password" autocomplete="new-password" minlength="15" required></label><label>Neues Passwort wiederholen<input type="password" name="confirm" autocomplete="new-password" required></label><button class="primary">Passwort speichern</button></form></section>
<?php else: ?>
<nav class="stage-nav" aria-label="Arbeitsbereiche"><a href="/zugang/">Mein Unterricht</a><?php if($teacher): ?><a href="/zugang/?view=classes">Klassen</a><?php if(Identity::allows($identity,'learning')): ?><a href="/zugang/arbeiten/">Schülerstände</a><?php endif; ?><a href="/lehrer/?view=profile">Mein Konto</a><?php endif; ?><?php if($admin): ?><a href="/zugang/?view=admin">Konten und Angebote</a><a href="/zugang/?view=installations">Prüfungsapp verbinden</a><a href="/lehrer/">Weitere Administration</a><?php endif; ?></nav>
<?php if($view==='admin' && $admin): ?>
<h1>Konten und Angebote</h1><p>Lege fest, wer LernHTML, Prüfungsapp oder beides verwenden kann. Klassen bestimmen, welche Arbeitsstände die Lehrkraft sieht.</p>
<details class="panel portal-section"><summary>Angebote je Organisation</summary><p>Eine Organisationssperre gilt zusätzlich zu den persönlichen Freigaben. Bestehende Arbeiten bleiben erhalten.</p><?php foreach(Portal::organisations($teacher) as $org): $enabled=[]; $q=ReligionPlatform\Database::connection()->prepare('SELECT product,enabled FROM platform_org_products WHERE organisation_id=?');$q->execute([$org['id']]);foreach($q->fetchAll() as $grant)$enabled[$grant['product']]=(bool)$grant['enabled']; ?><form method="post"><?php fields('set_org_products'); ?><h2><?= $h($org['name']) ?></h2><input type="hidden" name="organisation_id" value="<?= (int)$org['id'] ?>"><?php foreach(['learning'=>'LernHTML','assessment'=>'Prüfungsapp'] as $key=>$label): ?><label class="check"><input type="checkbox" name="products[]" value="<?= $key ?>" <?= ($enabled[$key] ?? true)?'checked':'' ?>><?= $label ?></label><?php endforeach; ?><button>Organisationsfreigaben speichern</button></form><?php endforeach; ?></details>
<div class="table-wrap"><table><thead><tr><th>Konto</th><th>Angebote</th><th>Zugang</th></tr></thead><tbody><?php foreach(Portal::accounts($teacher) as $account): ?><tr><td><strong><?= $h($account['display_name']) ?></strong><br><?= $h($account['username']) ?><br><small><?= $h(['admin'=>'Administration','teacher'=>'Lehrkraft','student'=>'Schülerkonto'][$account['role']]) ?></small></td><td><?php if($account['role']==='admin'): ?>Alle Angebote<?php else: ?><form method="post"><?php fields('set_products'); ?><input type="hidden" name="subject" value="<?= $h($account['subject']) ?>"><?php foreach(['learning'=>'LernHTML','assessment'=>'Prüfungsapp'] as $key=>$label): ?><label class="check"><input type="checkbox" name="products[]" value="<?= $key ?>" <?= $account[$key]?'checked':'' ?>><?= $label ?></label><?php endforeach; ?><button>Speichern</button></form><?php endif; ?></td><td><?= $account['status']==='active'?'Aktiv':'Gesperrt' ?><?php if($account['subject']!==$identity['subject']): ?><form method="post"><?php fields('set_status'); ?><input type="hidden" name="subject" value="<?= $h($account['subject']) ?>"><input type="hidden" name="status" value="<?= $account['status']==='active'?'suspended':'active' ?>"><button><?= $account['status']==='active'?'Sperren':'Freigeben' ?></button></form><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div>
<?php elseif($view==='installations' && $admin): ?>
<h1>Prüfungsapp verbinden</h1><p>Jede Installation gehört zu einer Organisation. Der gemeinsame Zugang gilt nur für dort berechtigte Konten.</p><div class="module-grid"><?php foreach(Portal::installations($identity) as $client): ?><article class="panel"><h2><?= $h($client['label']) ?></h2><p><?= $h($client['organisation_name']) ?><br><a href="<?= $h($client['base_url']) ?>"><?= $h($client['base_url']) ?></a></p><form method="post"><?php fields('client_status'); ?><input type="hidden" name="client_id" value="<?= $h($client['client_id']) ?>"><input type="hidden" name="status" value="<?= $client['status']==='active'?'suspended':'active' ?>"><button><?= $client['status']==='active'?'Verbindung sperren':'Verbindung freigeben' ?></button></form></article><?php endforeach; ?></div>
<details class="panel portal-section"><summary>Weitere Installation verbinden</summary><form method="post"><?php fields('register_client'); ?><input type="hidden" name="product" value="assessment"><label>Organisation<select name="organisation_id"><?php foreach(Portal::organisations($teacher) as $org): ?><option value="<?= (int)$org['id'] ?>"><?= $h($org['name']) ?></option><?php endforeach; ?></select></label><label>Bezeichnung<input name="label" required></label><label>Installationskennung<input name="client_id" pattern="[a-z][a-z0-9-]{2,63}" placeholder="pruefungsapp-schule" required></label><label>Adresse der Prüfungsapp<input type="url" name="base_url" placeholder="https://pruefungsapp.example.de" required></label><label>Rücksprungadresse<input type="url" name="redirect_uris" placeholder="https://pruefungsapp.example.de/api/platform/callback" required></label><button class="primary">Verbindungsschlüssel erstellen</button></form></details>
<?php elseif($view==='classes' && $teacher): ?>
<h1>Klassen</h1><div class="stage-nav"><?php foreach(SchoolDirectory::classes($teacher) as $class): ?><a href="/zugang/?view=classes&amp;class=<?= $h($class['id']) ?>"><?= $h($class['label'].' · '.$class['school_year']) ?></a><?php endforeach; ?></div>
<?php $classId=(string)($_GET['class'] ?? ''); if($classId): try { $class=SchoolDirectory::assertClass($teacher,$classId); $members=SchoolDirectory::learners($teacher,$classId); $write=$admin || in_array($class['class_role'],['owner','editor'],true); ?>
<section class="panel"><h2><?= $h($class['label']) ?></h2><p><?= $h($class['school_year']) ?></p><div class="table-wrap"><table><thead><tr><th>Nr.</th><th>Name</th><th>Anmeldename</th><th>Zugang</th></tr></thead><tbody><?php foreach($members as $member): ?><tr><td><?= (int)$member['roster_number'] ?></td><td><?= $h($member['display_name']) ?></td><td><?= $h($member['username']) ?></td><td><?= $member['must_change_password']?'Erste Anmeldung offen':'Eingerichtet' ?><?php if($write): ?><form method="post"><?php fields('reset_learner'); ?><input type="hidden" name="class_id" value="<?= $h($classId) ?>"><input type="hidden" name="subject" value="<?= $h($member['subject']) ?>"><button>Neues Startpasswort</button></form><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div>
<?php if($write): ?><details class="portal-section"><summary>Schülerkonto ergänzen</summary><form method="post"><?php fields('create_learner'); ?><input type="hidden" name="class_id" value="<?= $h($classId) ?>"><div class="form-grid"><label>Name<input name="name" required></label><label>Anmeldename<input name="username" placeholder="13R01" required></label><label>Listennummer<input type="number" name="number" min="1" max="999" required></label></div><?php foreach(['learning'=>'LernHTML','assessment'=>'Prüfungsapp'] as $key=>$label): if(Identity::allows($identity,$key,(int)$class['organisation_id'])): ?><label class="check"><input type="checkbox" name="products[]" value="<?= $key ?>" checked><?= $label ?></label><?php endif; endforeach; ?><button class="primary">Konto und Zugang anlegen</button></form></details><?php endif; ?>
<?php if($write): ?><details class="portal-section" <?= $pendingRoster?'open':'' ?>><summary>Klassenliste aus Excel oder Zwischenablage importieren</summary><p>Unterstützt XLSX, XLSM, CSV und Text. Alternativ Namen direkt aus Excel in das Textfeld einfügen. Vor dem Anlegen erscheint immer eine Vorschau; gleiche Namen werden niemals automatisch mit bestehenden Konten verbunden.</p><form method="post" enctype="multipart/form-data"><?php fields('roster_preview'); ?><input type="hidden" name="class_id" value="<?= $h($classId) ?>"><label>Datei auswählen<input type="file" name="roster_file" accept=".xlsx,.xlsm,.csv,.txt"></label><label>Oder aus der Zwischenablage einfügen<textarea name="roster_text" placeholder="1; Muster; Mia&#10;2; Beispiel; Ben"></textarea></label><label>Spaltenfolge<select name="column_mode"><option value="last_first">Nachname, Vorname</option><option value="first_last">Vorname, Nachname</option><option value="one">Ganzer Name in einer Spalte</option></select></label><?php foreach(['learning'=>'LernHTML','assessment'=>'Prüfungsapp'] as $key=>$label): if(Identity::allows($identity,$key,(int)$class['organisation_id'])): ?><label class="check"><input type="checkbox" name="products[]" value="<?= $key ?>" checked><?= $label ?></label><?php endif; endforeach; ?><button class="primary">Import prüfen</button></form><?php if($pendingRoster && $pendingRoster['class_id']===$classId): $plan=$pendingRoster['plan']; ?><section class="panel"><h3>Vorschau: <?= count($plan['learners']) ?> Personen</h3><div class="table-wrap"><table><thead><tr><th>Nr.</th><th>Name</th><th>Anmeldename</th><th>Aktion</th></tr></thead><tbody><?php foreach($plan['learners'] as $person): ?><tr><td><?= (int)$person['number'] ?></td><td><?= $h($person['name']) ?></td><td><?= $h($person['username']) ?></td><td><?= $h($person['action']) ?></td></tr><?php endforeach; ?></tbody></table></div><?php if($plan['conflicts']): ?><p class="alert error"><?= $h(implode(' ',$plan['conflicts'])) ?></p><?php else: ?><form method="post"><?php fields('roster_import'); ?><input type="hidden" name="preview_token" value="<?= $h($pendingRoster['token']) ?>"><button class="primary">Geprüfte Liste verbindlich anlegen</button></form><?php endif; ?></section><?php endif; ?></details><?php endif; ?>
<?php if($write): ?><details class="portal-section"><summary>Klasse bearbeiten oder archivieren</summary><form method="post"><?php fields('update_class'); ?><input type="hidden" name="class_id" value="<?= $h($classId) ?>"><label>Klassenname<input name="label" value="<?= $h($class['label']) ?>" required></label><label>Schuljahr<input name="school_year" value="<?= $h($class['school_year']) ?>" required></label><label>Status<select name="status"><option value="active" <?= $class['status']==='active'?'selected':'' ?>>Aktiv</option><option value="archived" <?= $class['status']==='archived'?'selected':'' ?>>Archiviert</option></select></label><p>Archivieren erhält die Mitschriften bis zum jeweiligen Aufbewahrungsende. Neue Bearbeitungen und die gemeinsame Prüfungsapp-Freigabe dieser Klasse enden.</p><button>Klasse speichern</button></form></details><?php endif; ?>
<details class="portal-section"><summary>Zugewiesene Lehrkräfte</summary><?php foreach(SchoolDirectory::teachers($teacher,$classId) as $assignedTeacher): ?><p><?= $h($assignedTeacher['display_name']) ?> · <?= $h(['owner'=>'Verantwortlich','editor'=>'Bearbeiten','viewer'=>'Lesen'][$assignedTeacher['role']]) ?><?= $assignedTeacher['status']!=='active'?' · gesperrt':'' ?></p><?php if($admin): ?><form method="post"><?php fields('set_teacher'); ?><input type="hidden" name="class_id" value="<?= $h($classId) ?>"><input type="hidden" name="teacher_id" value="<?= (int)$assignedTeacher['id'] ?>"><input type="hidden" name="role" value=""><button>Diese Klassenzuordnung entfernen</button></form><?php endif; endforeach; ?></details>
<?php if($admin): ?><details class="portal-section"><summary>Vorhandenes Schülerkonto zuordnen oder aus der Klasse nehmen</summary><p>Die Personenkennung und bisherige Arbeiten bleiben erhalten. Für einen Klassenwechsel erst die neue Klasse zuweisen und anschließend die bisherige Zuordnung deaktivieren. Ein gemeinsamer Name führt nie automatisch zu einer Kontoverknüpfung.</p><form method="post"><?php fields('set_learner_membership'); ?><input type="hidden" name="class_id" value="<?= $h($classId) ?>"><label>Bestehende Person<select name="subject"><?php foreach(SchoolDirectory::learnerCandidates($teacher,$classId) as $candidate): ?><option value="<?= $h($candidate['subject']) ?>"><?= $h($candidate['display_name'].' · '.$candidate['username']) ?></option><?php endforeach; ?></select></label><label>Listennummer<input name="number" type="number" min="1" max="999" required></label><label>Zuordnung<select name="active"><option value="1">In dieser Klasse aktiv</option><option value="0">Nicht mehr in dieser Klasse</option></select></label><button>Zuordnung speichern</button></form></details><?php endif; ?>
<?php if($admin): ?><details class="portal-section"><summary>Lehrkraft zuweisen</summary><form method="post"><?php fields('set_teacher'); ?><input type="hidden" name="class_id" value="<?= $h($classId) ?>"><label>Lehrkraft<select name="teacher_id"><?php foreach(SchoolDirectory::teacherCandidates($teacher,$classId) as $candidate): ?><option value="<?= (int)$candidate['id'] ?>"><?= $h($candidate['display_name']) ?></option><?php endforeach; ?></select></label><label>Berechtigung<select name="role"><option value="editor">Bearbeiten und einsehen</option><option value="viewer">Nur einsehen</option><option value="owner">Verantwortliche Lehrkraft</option><option value="">Zuordnung entfernen</option></select></label><button>Zuordnung speichern</button></form></details><?php endif; ?></section>
<?php } catch(Throwable $exception) { ?><p class="alert error"><?= $h($exception->getMessage()) ?></p><?php } endif; ?>
<details class="panel portal-section"><summary>Klasse anlegen</summary><form method="post"><?php fields('create_class'); ?><label>Organisation<select name="organisation_id"><?php foreach(Portal::organisations($teacher) as $org): ?><option value="<?= (int)$org['id'] ?>"><?= $h($org['name']) ?></option><?php endforeach; ?></select></label><label>Klassenname<input name="label" required></label><label>Schuljahr<input name="school_year" placeholder="2026/27" required></label><button class="primary">Klasse anlegen</button></form></details>
<?php else: ?>
<h1><?= $h($identity['display_name']) ?>, dein Unterricht</h1>
<?php if($identity['kind']==='student'): ?><details class="panel portal-section"><summary>Mein Passwort ändern</summary><form method="post"><?php fields('student_password'); ?><label>Bisheriges Passwort<input type="password" name="current" autocomplete="current-password" required></label><label>Neues Passwort · mindestens 15 Zeichen<input type="password" name="password" autocomplete="new-password" minlength="15" required></label><label>Neues Passwort wiederholen<input type="password" name="confirm" autocomplete="new-password" required></label><button>Passwort speichern</button></form></details><?php endif; ?>
<div class="module-grid">
<?php if(Identity::allows($identity,'learning')): ?><article class="panel"><span class="pill">LernHTML</span><h2>Lernwege und Mitschriften</h2><?php if($teacher): ?><p>Öffne einen Lernweg, bereite deinen Raum vor und begleite deine Klasse.</p><a class="button primary" href="/lehrer/">LernHTMLs öffnen</a><?php else: ?><p>Deine zugewiesenen Lernwege findest du hier. Darin wird deine Mitschrift automatisch für die Lehrkräfte deiner Klasse gespeichert. Ohne Zuweisung kannst du öffentliche Lernwege weiterhin lokal bearbeiten.</p><?php endif; ?></article><?php endif; ?>
<?php foreach(Portal::installations($identity) as $client): if($client['status']!=='active' || !Identity::allows($identity,$client['product'],(int)$client['organisation_id'])) continue; ?><article class="panel"><span class="pill">Prüfungsapp</span><h2><?= $h($client['label']) ?></h2><p><?= $teacher?'Prüfungen und Übungen vorbereiten, durchführen und zurückgeben.':'Deine Prüfungen, Übungen und Rückgaben.' ?></p><a class="button primary" href="<?= $h($client['base_url'].'/api/platform/start') ?>">Prüfungsapp öffnen</a></article><?php endforeach; ?>
<?php if($identity['kind']==='student'): foreach(ReligionPlatform\LearningWork::assignments($identity) as $assignment): ?><article class="panel"><span class="pill">LernHTML · <?= $h($assignment['class_label']) ?></span><h2><?= $h($assignment['label']) ?></h2><p><?= $h($assignment['module_label']) ?><br>Lehrkraft: <?= $h($assignment['teacher_name']) ?></p><p><small>Deine Mitschrift wird automatisch gespeichert und ist für die zugewiesenen Lehrkräfte einsehbar. Aufbewahrung bis <?= date('d.m.Y',(int)$assignment['retain_until']) ?>.</small></p><a class="button primary" href="<?= $h($assignment['public_url'].'?'.http_build_query(['arbeit'=>$assignment['id']]+($assignment['room_code']?['room'=>$assignment['room_code']]:[]))) ?>"><?= $assignment['status']==='active'?'Lernweg öffnen':'Mitschrift ansehen' ?></a></article><?php endforeach; endif; ?>
</div><?php endif; endif; ?>
</main><footer><a href="/datenschutz-lernplattform/">Datenschutz</a> · <a href="/support-anfragen/">Hilfe und Rückmeldung</a></footer></body></html>
